export default interface Move {
    id: number,
    name: string,
    damageBase: number,
    frequency: string,
    ac: number,
    range: string,
    effects: string,
    constestStats: string,
    category: string,
    type: string,
    sheerForce: boolean,
    toughClaws: boolean,
    technician: boolean,
    reckless: boolean,
    ironFist: boolean,
    megaLauncher: boolean,
    punkRock: boolean,
    strongJaw: boolean
}